baseURL = 'https://success-solutions.netlify.app/'
languageCode = 'en-us'
title = 'Success Solutions HR Consulting | Expatriate Hiring'
theme = 'HR-website'
[params]
favicon = '/favicon.ico'
description = 'Success Solutions specializes in expatriate hiring and global executive search, helping businesses build exceptional teams. With ethical hiring practices, confidentiality assurance, and a focus on quality, we provide innovative and tailored solutions to drive organizational success and growth.'
keywords = 'expatriate hiring, global executive search, leadership hiring, business consulting, recruitment solutions, talent acquisition, organizational growth, ethical hiring practices, Success Solutions, hiring methodology, corporate hiring, human resource management, executive search services'
author = 'Balachandiran - TenSketch'
logo = '/images/logo/Success-Solutions-logo-2.jpeg'
og_image = '/ogimage.jpg'
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[asset]
  # Enable Hugo pipes for SCSS
  enable = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About Us"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "Approach"
    url = "/our-approach/"
    weight = 3

    [[menu.main]]
      name = "Core Belief"
      parent = "Approach"
      url = "/our-approach/core-belief/"
      weight = 1

    [[menu.main]]
      name = "Consulting Practice"
      parent = "Approach"
      url = "/our-approach/consulting-practice/"
      weight = 2

    [[menu.main]]
      name = "Consistent Expertise"
      parent = "Approach"
      url = "/our-approach/consistent-expertise/"
      weight = 3

  [[menu.main]]
    name = "Core Services"
    url = "/core-services/"
    weight = 4

    [[menu.main]]
      name = "Expat Hiring Methodologies"
      parent = "Core Services"
      url = "/core-services/expat-hiring-methodologies/"
      weight = 1

    [[menu.main]]
      name = "Hiring SBU's Vertical"
      parent = "Core Services"
      url = "/core-services/hiring-sbu-verticals/"
      weight = 2

    [[menu.main]]
      name = "Allied Services"
      parent = "Core Services"
      url = "/core-services/allied-services/"
      weight = 3

  [[menu.main]]
    name = "Downloads"
    url = "/downloads/"
    weight = 5

  [[menu.main]]
    name = "Contact Us"
    url = "/contact/"
    weight = 6
